# .github/workflows/ci.yml
name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  # Этот джоб отвечает за линтинг
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
            go-version: '1.26.3' # или '1.26.3', если go.mod не используется

      - name: Show go.mod and directory
        run: |
          pwd
          cat go.mod
          ls -la

      - name: Tidy go module
        run: go mod tidy

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v9
        with:
            version: v2.9.0
            args: ./...