# .github/workflows/ci.yml
name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  # Этот джоб отвечает за линтинг
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
            go-version-file: 'go.mod' # или '1.26.3', если go.mod не используется

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v9
        with:
            # Версия linter, собранная с Go 1.26
            version: v2.9.0